export enum adminTypes {
	GET_USERS_SAGA = '@@ADMIN/GET_USERS_SAGA',
	GET_ADS_SAGA = '@@ADMIN/GET_ADS',
	SET_USERS_LOADER = '@@ADMIN/SET_USERS_LOADER',
	SET_ADS_LOADER = '@@ADMIN/SET_ADS_LOADER',
	SET_USERS = '@@ADMIN/SET_USERS',
	SET_ADS = '@@ADMIN/SET_ADS'
}
