export enum AppTypes {
	INITIALIZED_SUCCESS = '@@APP/INITIALIZED_SUCCESS',
	SHOW_MESSAGE = '@@APP/SHOW_MESSAGE',
	DELETE_MESSAGE = '@@APP/DELETE_MESSAGE',
	SET_GLOBAL_LOADER = '@@APP/SET_GLOBAL_LOADER',
	SET_PUBLIC_HEADER_VISIBLE = '@@APP/SET_PUBLIC_HEADER_VISIBLE'
}
