export enum RubricTypes {
	GET_RUBRICS_SAGA = '@@APP/GET_RUBRICS_SAGA',
	SET_RUBRIC = '@@APP/GET_RUBRICS_SAGA',

	GET_DIRECTIONS_SAGA = '@@APP/GET_DIRECTIONS_SAGA',
	SET_DIRECTIONS = '@@APP/SET_DIRECTIONS',

	GET_SPECIALTIES_SAGA = '@@APP/GET_SPECIALTIES_SAGA',
	SET_SPECIALTIES = '@@APP/SET_SPECIALTIES',

	GET_SPECIALIZATIONS_SAGA = '@@APP/GET_SPECIALIZATIONS_SAGA',
	SET_SPECIALIZATIONS = '@@APP/SET_SPECIALIZATIONS'
}
